In [1]:
a=[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [2]:
a[0]

[1, 2, 3, 4, 5]

In [3]:
a[1]

[6, 7, 8, 9, 10]

In [9]:
#  An array is a vector containing homogeneous elements i.e. belonging to the same data type.
# Elements are allocated with contiguous memory locations allowing easy modification
# , that is, addition, deletion, accessing of elements.
# In Python, we have to use the array module to declare arrays.
# If the elements of an array belong to different data types, an exception “Incompatible data types” is thrown.

# There are no arrays directly in python. They are basically predefined objects created using numpy.

In [20]:
import numpy as np
a=[1, 2, '3', "hello"]

In [24]:
np.array(a)
# automatically converts integers to string to maintain homogeneity

array(['1', '2', '3', 'hello'], dtype='<U11')

In [25]:
b=[1, 2, 3, 4, 5]
np.array(b)

array([1, 2, 3, 4, 5])

In [29]:
c = [[1, 2], [3, 4]];
print(type(c))
d = np.array(c)
print(type(d))

<class 'list'>
<class 'numpy.ndarray'>


In [35]:
print(d.ndim)

2


In [36]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [37]:
np.full((2, 2), np.inf)

array([[inf, inf],
       [inf, inf]])

In [39]:
np.full((2, 2), 10)


array([[10, 10],
       [10, 10]])

In [40]:
np.full((2, 2), [1, 2])

array([[1, 2],
       [1, 2]])

In [43]:
(np.eye(2, dtype=int))

array([[1, 0],
       [0, 1]])

In [44]:
(np.eye(4, dtype=float))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
np.ones((2, 2), dtype=int)

array([[1, 1],
       [1, 1]])

In [47]:
np.ones(2, dtype=int)

array([1, 1])

In [59]:
np.random.random((2, 2))
# Exactly same as .rand, only format of input arguments different

array([[0.50144602, 0.89153247],
       [0.60933144, 0.8443588 ]])

In [60]:
np.random.rand(3, 2)

array([[0.94529809, 0.51690965],
       [0.21814156, 0.04414888],
       [0.50509541, 0.97610695]])

In [61]:
np.random.random((3, 2))

array([[0.25332244, 0.12841603],
       [0.31907374, 0.51281496],
       [0.62233052, 0.19865366]])

In [62]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [65]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
np.zeros((5, 6), dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [71]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
x.shape, y.shape

((2, 2), (2, 2))

In [72]:
x+y

array([[ 6,  8],
       [10, 12]])

In [73]:
np.add(x, y)

array([[ 6,  8],
       [10, 12]])

In [75]:
print(x-y,'\n', np.subtract(x, y))

[[-4 -4]
 [-4 -4]] 
 [[-4 -4]
 [-4 -4]]


In [78]:
# This is element wise multication, not matrix multiplication
x*y

array([[ 5, 12],
       [21, 32]])

In [79]:
# This is element wise multication, not matrix multiplication
np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

In [81]:
# This is normal matrix multiplication
np.matmul(x, y)

array([[19, 22],
       [43, 50]])

In [82]:
np.matmul(x, x, y)

array([[ 7, 10],
       [15, 22]])

In [83]:
np.matmul(y, x, y)

array([[ 37,  54],
       [ 81, 118]])

In [84]:
# Element wise divide
x/y

array([[0.02702703, 0.03703704],
       [0.03703704, 0.03389831]])

In [85]:
np.divide(x, y)

array([[0.02702703, 0.03703704],
       [0.03703704, 0.03389831]])

In [89]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [91]:
# This is normal matrix multiplication only, not the dot product
x.dot(y)

array([[199, 290],
       [435, 634]])

In [115]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])
# Creating 2-d array using 2 1-d arrays
print(np.array([a, b]))
# This is normal dot product
a.dot(b)

[[1 2 3 4 5]
 [1 2 3 4 5]]


55

In [116]:
a[0]

1

In [117]:
a[0]=7

In [118]:
print(a, b)

[7 2 3 4 5] [1 2 3 4 5]


In [119]:
sum(a)

21

In [120]:
np.sum(a)

21

In [121]:
a.dot(np.ones(5, dtype=int))

21

In [122]:
c = np.array([[1, 2, 3], [1, 2, 3]])

In [123]:
# Columnwise sum
np.sum(c, axis=0)

array([2, 4, 6])

In [124]:
# Rowise sum
np.sum(c, axis=1)

array([6, 6])

In [128]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9]])
x[0, 1]

2

In [133]:
sum = 0;
for i in range(0, 3):
    for j in range(0, 3):
        sum = sum + x[i, j]
print(sum)

sumCol = np.zeros(x.shape[0], dtype=int)
sumColb

45


array([0, 0, 0])

In [136]:
sumCol

array([0, 0, 0])

In [138]:
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        sumCol[j] = sumCol[j] + x[i][j]
sumCol

array([12, 15, 18])

In [143]:
a = np.array([1, 2, 3, 4, 5])
b = a

In [144]:
b = b**2

In [145]:
b

array([ 1,  4,  9, 16, 25])

In [146]:
a

array([1, 2, 3, 4, 5])

In [150]:
# Stacking along y-axis
c = np.stack((a, b), axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [153]:
# Stacking along x-axis
np.stack((a, b), axis=1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25]])

In [157]:
# Returns the reshaped matrix, doesn't alter the input matrix, also doesn't reduce the dimension
# Retains the original dimensions
c.reshape((1, 10))

array([[ 1,  1,  2,  4,  3,  9,  4, 16,  5, 25]])

In [155]:
c

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25]])

In [158]:
# If we know no. of rows or columns, we can put -1 so that it automatically finds out
c.reshape((5, -1))

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25]])

In [159]:
# To convert into a vector from a matrix
c.ravel()

array([ 1,  1,  2,  4,  3,  9,  4, 16,  5, 25])

In [164]:
# starting point, ending point, step
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [165]:
np.arange(10) + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [167]:
np.array([0, 0, 0, 0, 0]) + 5

array([5, 5, 5, 5, 5])

In [174]:
# Shuffles the data set, can be used for matrix as well
# Doesn't return, alters the input matrix
np.random.shuffle(c)

In [173]:
c

array([[ 5, 25],
       [ 3,  9],
       [ 2,  4],
       [ 4, 16],
       [ 1,  1]])

In [186]:
# To get random numbers from 0 to 10
# Uniform Distribution
r = np.random.rand(5, 5) * 10
print(r)

[[6.9402526  9.8015738  7.14925309 2.21265332 4.54703846]
 [0.34833238 8.48886973 2.1760806  0.27813676 8.37801795]
 [0.95217802 9.04485282 7.87773146 4.80185067 1.59891203]
 [0.43092879 4.47157881 9.13500861 4.33025006 3.49900688]
 [4.1070816  3.55028707 2.5159704  9.84006988 7.62837179]]


In [190]:
# Standard Normal Distribution
r = np.random.randn(5, 5)
print(r)

[[-0.18711304 -0.94432393  0.22659652  0.75218686  0.8103005 ]
 [-0.73979639  0.80656485  1.01621183  0.40973125 -0.85946114]
 [-0.73698293  0.72308712 -1.07399951  1.29014879 -1.29442973]
 [-0.89959364 -0.29825196  0.01597034  0.27792805 -0.96110662]
 [ 0.13552337 -0.71868451 -0.61663931 -0.00705581 -0.14289384]]


In [195]:
# Start, end, size of array of random integers
np.random.randint(5, 10, (10, 2))

array([[5, 9],
       [9, 7],
       [5, 8],
       [9, 7],
       [5, 9],
       [6, 8],
       [6, 7],
       [9, 7],
       [6, 5],
       [7, 7]])

In [198]:
# To randomly choose a number from an array - but only possible from 1-d array
np.random.choice(r.ravel())

-0.9611066191874169